/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoGrafico;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumno
 */
public class formularioPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form formularioPrincipal
     */
    public formularioPrincipal() {
        initComponents();
        crearConexionBBDD();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelTab = new javax.swing.JTabbedPane();
        tabPrincipal = new javax.swing.JPanel();
        panelGestionDiariaPpal = new javax.swing.JPanel();
        botonGestionDepar = new javax.swing.JButton();
        botonGestionEmple = new javax.swing.JButton();
        panelMantenimientoDiarioPpal = new javax.swing.JPanel();
        panelEtiqueta = new javax.swing.JPanel();
        etiquetaGestion = new javax.swing.JLabel();
        tabDepartamentos = new javax.swing.JPanel();
        panelGestionDepar = new javax.swing.JPanel();
        etiqIdDepar = new javax.swing.JLabel();
        textIdDepart = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textNombreDepar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textLocDepar = new javax.swing.JTextField();
        panelBusquedaBBDD = new javax.swing.JPanel();
        btnPrim = new javax.swing.JButton();
        btnSig = new javax.swing.JButton();
        btnAnt = new javax.swing.JButton();
        btnUlt = new javax.swing.JButton();
        panelInsModBorr = new javax.swing.JPanel();
        btnInsertar = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        tabEmpleados = new javax.swing.JPanel();
        panelGestEmple = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        panelBusqEmple = new javax.swing.JPanel();
        btnPrimEmple = new javax.swing.JButton();
        btnSigEmple = new javax.swing.JButton();
        btnAntEmple = new javax.swing.JButton();
        btnUltEmple = new javax.swing.JButton();
        panelAdminEmple = new javax.swing.JPanel();
        btnInsertEmple = new javax.swing.JButton();
        btnModfEmple = new javax.swing.JButton();
        btnBorrEmple = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelGestionDiariaPpal.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión Diaria"));

        botonGestionDepar.setText("Gestión de Departamentos");
        botonGestionDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionDeparActionPerformed(evt);
            }
        });

        botonGestionEmple.setText("Gestión de Empleados");
        botonGestionEmple.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonGestionEmpleActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelGestionDiariaPpalLayout = new javax.swing.GroupLayout(panelGestionDiariaPpal);
        panelGestionDiariaPpal.setLayout(panelGestionDiariaPpalLayout);
        panelGestionDiariaPpalLayout.setHorizontalGroup(
            panelGestionDiariaPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionDiariaPpalLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(panelGestionDiariaPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonGestionDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonGestionEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGestionDiariaPpalLayout.setVerticalGroup(
            panelGestionDiariaPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionDiariaPpalLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(botonGestionDepar)
                .addGap(35, 35, 35)
                .addComponent(botonGestionEmple)
                .addContainerGap(117, Short.MAX_VALUE))
        );

        panelMantenimientoDiarioPpal.setBorder(javax.swing.BorderFactory.createTitledBorder("Mantenimiento"));

        javax.swing.GroupLayout panelMantenimientoDiarioPpalLayout = new javax.swing.GroupLayout(panelMantenimientoDiarioPpal);
        panelMantenimientoDiarioPpal.setLayout(panelMantenimientoDiarioPpalLayout);
        panelMantenimientoDiarioPpalLayout.setHorizontalGroup(
            panelMantenimientoDiarioPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 395, Short.MAX_VALUE)
        );
        panelMantenimientoDiarioPpalLayout.setVerticalGroup(
            panelMantenimientoDiarioPpalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        etiquetaGestion.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        etiquetaGestion.setText("Aplicación Gestión Acceso a Datos");

        javax.swing.GroupLayout panelEtiquetaLayout = new javax.swing.GroupLayout(panelEtiqueta);
        panelEtiqueta.setLayout(panelEtiquetaLayout);
        panelEtiquetaLayout.setHorizontalGroup(
            panelEtiquetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEtiquetaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(etiquetaGestion)
                .addGap(234, 234, 234))
        );
        panelEtiquetaLayout.setVerticalGroup(
            panelEtiquetaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEtiquetaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(etiquetaGestion, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabPrincipalLayout = new javax.swing.GroupLayout(tabPrincipal);
        tabPrincipal.setLayout(tabPrincipalLayout);
        tabPrincipalLayout.setHorizontalGroup(
            tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(tabPrincipalLayout.createSequentialGroup()
                        .addComponent(panelGestionDiariaPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelMantenimientoDiarioPpal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        tabPrincipalLayout.setVerticalGroup(
            tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabPrincipalLayout.createSequentialGroup()
                .addComponent(panelEtiqueta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tabPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panelMantenimientoDiarioPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelGestionDiariaPpal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        panelTab.addTab("Principal", tabPrincipal);

        tabDepartamentos.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tabDepartamentosComponentShown(evt);
            }
        });

        panelGestionDepar.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de departamentos"));

        etiqIdDepar.setText("ID Departamento");

        jLabel2.setText("Nombre Departamento");

        textNombreDepar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textNombreDeparActionPerformed(evt);
            }
        });

        jLabel3.setText("Localidad Departamento");

        javax.swing.GroupLayout panelGestionDeparLayout = new javax.swing.GroupLayout(panelGestionDepar);
        panelGestionDepar.setLayout(panelGestionDeparLayout);
        panelGestionDeparLayout.setHorizontalGroup(
            panelGestionDeparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionDeparLayout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addGroup(panelGestionDeparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGestionDeparLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textNombreDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelGestionDeparLayout.createSequentialGroup()
                        .addComponent(etiqIdDepar)
                        .addGap(96, 96, 96)
                        .addComponent(textIdDepart, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGestionDeparLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textLocDepar, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelGestionDeparLayout.setVerticalGroup(
            panelGestionDeparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestionDeparLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestionDeparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiqIdDepar)
                    .addComponent(textIdDepart, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionDeparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textNombreDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestionDeparLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(textLocDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelBusquedaBBDD.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        btnPrim.setText("Primero");
        btnPrim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimActionPerformed(evt);
            }
        });

        btnSig.setText("Siguiente");
        btnSig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigActionPerformed(evt);
            }
        });

        btnAnt.setText("Anterior");
        btnAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAntActionPerformed(evt);
            }
        });

        btnUlt.setText("Último");
        btnUlt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBusquedaBBDDLayout = new javax.swing.GroupLayout(panelBusquedaBBDD);
        panelBusquedaBBDD.setLayout(panelBusquedaBBDDLayout);
        panelBusquedaBBDDLayout.setHorizontalGroup(
            panelBusquedaBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBusquedaBBDDLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPrim, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSig, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUlt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(197, 197, 197))
        );
        panelBusquedaBBDDLayout.setVerticalGroup(
            panelBusquedaBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusquedaBBDDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusquedaBBDDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrim)
                    .addComponent(btnSig)
                    .addComponent(btnAnt)
                    .addComponent(btnUlt))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panelInsModBorr.setBorder(javax.swing.BorderFactory.createTitledBorder("Administración"));

        btnInsertar.setText("INSERTAR");
        btnInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarActionPerformed(evt);
            }
        });

        btnModif.setText("MODIFICAR");

        btnBorrar.setText("BORRAR");

        javax.swing.GroupLayout panelInsModBorrLayout = new javax.swing.GroupLayout(panelInsModBorr);
        panelInsModBorr.setLayout(panelInsModBorrLayout);
        panelInsModBorrLayout.setHorizontalGroup(
            panelInsModBorrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsModBorrLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );
        panelInsModBorrLayout.setVerticalGroup(
            panelInsModBorrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInsModBorrLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInsModBorrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModif, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabDepartamentosLayout = new javax.swing.GroupLayout(tabDepartamentos);
        tabDepartamentos.setLayout(tabDepartamentosLayout);
        tabDepartamentosLayout.setHorizontalGroup(
            tabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelGestionDepar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelBusquedaBBDD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelInsModBorr, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tabDepartamentosLayout.setVerticalGroup(
            tabDepartamentosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabDepartamentosLayout.createSequentialGroup()
                .addComponent(panelGestionDepar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBusquedaBBDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInsModBorr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        panelTab.addTab("Departamentos", tabDepartamentos);

        panelGestEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Gestión de empleados"));

        jLabel1.setText("Apellido");

        jLabel4.setText("Oficio");

        jLabel5.setText("Salario");

        jLabel6.setText("Comisión");

        jLabel7.setText("Número de empleado");

        jLabel8.setText("Directorio");

        jLabel9.setText("Número de departamento");

        jLabel10.setText("Fecha de alta");

        javax.swing.GroupLayout panelGestEmpleLayout = new javax.swing.GroupLayout(panelGestEmple);
        panelGestEmple.setLayout(panelGestEmpleLayout);
        panelGestEmpleLayout.setHorizontalGroup(
            panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestEmpleLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelGestEmpleLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGestEmpleLayout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGestEmpleLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelGestEmpleLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(37, 37, 37)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(146, 146, 146)
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addGap(30, 30, 30)
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelGestEmpleLayout.setVerticalGroup(
            panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGestEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGestEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelBusqEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Búsqueda"));

        btnPrimEmple.setText("Primero");

        btnSigEmple.setText("Siguiente");

        btnAntEmple.setText("Anterior");

        btnUltEmple.setText("Último");

        javax.swing.GroupLayout panelBusqEmpleLayout = new javax.swing.GroupLayout(panelBusqEmple);
        panelBusqEmple.setLayout(panelBusqEmpleLayout);
        panelBusqEmpleLayout.setHorizontalGroup(
            panelBusqEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusqEmpleLayout.createSequentialGroup()
                .addGap(195, 195, 195)
                .addComponent(btnPrimEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSigEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAntEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnUltEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBusqEmpleLayout.setVerticalGroup(
            panelBusqEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBusqEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBusqEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSigEmple)
                    .addComponent(btnAntEmple)
                    .addComponent(btnUltEmple)
                    .addComponent(btnPrimEmple))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelAdminEmple.setBorder(javax.swing.BorderFactory.createTitledBorder("Adiministración"));

        btnInsertEmple.setText("INSERTAR");

        btnModfEmple.setText("MODIFICAR");

        btnBorrEmple.setText("BORRAR");

        javax.swing.GroupLayout panelAdminEmpleLayout = new javax.swing.GroupLayout(panelAdminEmple);
        panelAdminEmple.setLayout(panelAdminEmpleLayout);
        panelAdminEmpleLayout.setHorizontalGroup(
            panelAdminEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminEmpleLayout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(btnInsertEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addComponent(btnModfEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnBorrEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(86, Short.MAX_VALUE))
        );
        panelAdminEmpleLayout.setVerticalGroup(
            panelAdminEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminEmpleLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAdminEmpleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnInsertEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModfEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBorrEmple, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tabEmpleadosLayout = new javax.swing.GroupLayout(tabEmpleados);
        tabEmpleados.setLayout(tabEmpleadosLayout);
        tabEmpleadosLayout.setHorizontalGroup(
            tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabEmpleadosLayout.createSequentialGroup()
                .addGroup(tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panelGestEmple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAdminEmple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBusqEmple, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        tabEmpleadosLayout.setVerticalGroup(
            tabEmpleadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabEmpleadosLayout.createSequentialGroup()
                .addComponent(panelGestEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBusqEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAdminEmple, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelTab.addTab("Empleados", tabEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
/**/
    private void crearConexionBBDD()
    {
        try 
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://localhost/bbdd_ejemplo1","root","admin");
        }
        catch (ClassNotFoundException | SQLException ex) 
        {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void mostrarDatosBBDD()
    {
        try
        {
            textIdDepart.setText(Integer.toString(result.getInt("dept_no")));
            textNombreDepar.setText(result.getString("dnombre"));
            textLocDepar.setText(result.getString("loc"));
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    private void botonGestionDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionDeparActionPerformed
        // TODO add your handling code here:
        panelTab.setSelectedComponent(tabDepartamentos);
    }//GEN-LAST:event_botonGestionDeparActionPerformed

    private void textNombreDeparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textNombreDeparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textNombreDeparActionPerformed

    private void btnInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarActionPerformed
        // TODO add your handling code here:
        panelBusquedaBBDD.setVisible(false);
    }//GEN-LAST:event_btnInsertarActionPerformed

    private void botonGestionEmpleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGestionEmpleActionPerformed
        // TODO add your handling code here:
        panelTab.setSelectedComponent(tabEmpleados);
    }//GEN-LAST:event_botonGestionEmpleActionPerformed

    private void btnPrimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimActionPerformed
        
        try
        {
            if(result.isFirst() == true)
            {
                JOptionPane.showMessageDialog(null,"Ya estás en la primera posición");
            }
            else
            {
                result.first();
                textIdDepart.setText(Integer.toString(result.getInt("dept_no")));
                textNombreDepar.setText(result.getString("dnombre"));
                textLocDepar.setText(result.getString("loc"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnPrimActionPerformed

    private void btnSigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigActionPerformed
        try {
            // TODO add your handling code here:
            if(result.isLast() == true)
            {
                JOptionPane.showMessageDialog(null, "No hay más resultados en la base de datos.");
            }
            else
            {
                result.next();
                textIdDepart.setText(Integer.toString(result.getInt("dept_no")));
                textNombreDepar.setText(result.getString("dnombre"));
                textLocDepar.setText(result.getString("loc"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSigActionPerformed

    private void btnAntActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAntActionPerformed
        try {
            // TODO add your handling code here:
            if(result.isFirst() == true)
            {
                JOptionPane.showMessageDialog(null,"Ya estás en la primera posición");
            }
            else
            {
                result.previous();
                textIdDepart.setText(Integer.toString(result.getInt("dept_no")));
                textNombreDepar.setText(result.getString("dnombre"));
                textLocDepar.setText(result.getString("loc"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnAntActionPerformed

    private void btnUltActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            if(result.isLast() == true)
            {
                JOptionPane.showMessageDialog(null,"No hay más resultados en la base de datos");
            }
            else
            {
                result.last();
                textIdDepart.setText(Integer.toString(result.getInt("dept_no")));
                textNombreDepar.setText(result.getString("dnombre"));
                textLocDepar.setText(result.getString("loc"));
            }
        } catch (SQLException ex) {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnUltActionPerformed

    private void tabDepartamentosComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tabDepartamentosComponentShown
        // TODO add your handling code here:
        String query = "SELECT * FROM departamentos";
        try
        {
            Statement sentencia = conexion.createStatement();
            result = sentencia.executeQuery(query);
                   
            result.first();
            mostrarDatosBBDD();
        }
        catch (SQLException ex) 
        {
            Logger.getLogger(formularioPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabDepartamentosComponentShown

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formularioPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formularioPrincipal().setVisible(true);
            }
        });
        
        
        // Variables para la conexión con la BBDD
        
        
        
    }
    // Mis atributos
    Connection conexion;
    ResultSet result;
      

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonGestionDepar;
    private javax.swing.JButton botonGestionEmple;
    private javax.swing.JButton btnAnt;
    private javax.swing.JButton btnAntEmple;
    private javax.swing.JButton btnBorrEmple;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnInsertEmple;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnModfEmple;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnPrim;
    private javax.swing.JButton btnPrimEmple;
    private javax.swing.JButton btnSig;
    private javax.swing.JButton btnSigEmple;
    private javax.swing.JButton btnUlt;
    private javax.swing.JButton btnUltEmple;
    private javax.swing.JLabel etiqIdDepar;
    private javax.swing.JLabel etiquetaGestion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JPanel panelAdminEmple;
    private javax.swing.JPanel panelBusqEmple;
    private javax.swing.JPanel panelBusquedaBBDD;
    private javax.swing.JPanel panelEtiqueta;
    private javax.swing.JPanel panelGestEmple;
    private javax.swing.JPanel panelGestionDepar;
    private javax.swing.JPanel panelGestionDiariaPpal;
    private javax.swing.JPanel panelInsModBorr;
    private javax.swing.JPanel panelMantenimientoDiarioPpal;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JPanel tabDepartamentos;
    private javax.swing.JPanel tabEmpleados;
    private javax.swing.JPanel tabPrincipal;
    private javax.swing.JTextField textIdDepart;
    private javax.swing.JTextField textLocDepar;
    private javax.swing.JTextField textNombreDepar;
    // End of variables declaration//GEN-END:variables
}